package report

import (
	"bytes"
	"html/template"
	"time"

	"github.com/ag/pruner/internal/cleanup"
	"github.com/ag/pruner/internal/compliance"
)

type NamespaceReport struct {
	Namespace   string
	ClusterURL  string
	OwnerEmail  string
	ScannedAt   time.Time
	TotalImages int
	Violations  []compliance.Violation
	JIRAKeys    []string
	Cleanup     cleanup.Result
}

func (r *NamespaceReport) CountBySeverity(severity string) int {
	n := 0
	for _, v := range r.Violations {
		if v.Severity == severity {
			n++
		}
	}
	return n
}

var htmlTemplate = template.Must(template.New("report").Parse(`
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 14px; color: #333; }
  h2   { color: #c00; }
  table { border-collapse: collapse; width: 100%; margin-top: 12px; }
  th   { background: #333; color: #fff; padding: 8px 12px; text-align: left; }
  td   { padding: 7px 12px; border-bottom: 1px solid #ddd; }
  tr:nth-child(even) { background: #f9f9f9; }
  .HIGH   { color: #c00; font-weight: bold; }
  .MEDIUM { color: #e67e00; font-weight: bold; }
  .LOW    { color: #888; }
  .summary-box { background: #f0f0f0; padding: 12px 16px; border-left: 4px solid #c00; margin-bottom: 16px; }
  .pill { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 12px; }
  .pill-red    { background: #fdd; color: #c00; }
  .pill-orange { background: #ffe8cc; color: #e67e00; }
  .pill-grey   { background: #eee; color: #555; }
</style>
</head>
<body>
<h2>Image Hygiene Report</h2>
<p><strong>Namespace:</strong> {{.Namespace}}<br>
<strong>Cluster:</strong> {{.ClusterURL}}<br>
<strong>Scanned:</strong> {{.ScannedAt.Format "2006-01-02 15:04 UTC"}}</p>

<div class="summary-box">
  <strong>Total Images:</strong> {{.TotalImages}} &nbsp;|&nbsp;
  <strong>Violations:</strong> {{len .Violations}} &nbsp;|&nbsp;
  <span class="pill pill-red">HIGH {{call .CountBySeverity "HIGH"}}</span> &nbsp;
  <span class="pill pill-orange">MEDIUM {{call .CountBySeverity "MEDIUM"}}</span> &nbsp;
  <span class="pill pill-grey">LOW {{call .CountBySeverity "LOW"}}</span>
</div>

{{if .Violations}}
<h3>Violations</h3>
<table>
  <tr>
    <th>Image</th>
    <th>Rule</th>
    <th>Age (days)</th>
    <th>Severity</th>
  </tr>
  {{range .Violations}}
  <tr>
    <td>{{.ImageRef}}</td>
    <td>{{.RuleType}}</td>
    <td>{{.AgeDays}}</td>
    <td class="{{.Severity}}">{{.Severity}}</td>
  </tr>
  {{end}}
</table>
{{else}}
<p style="color:green"><strong>✓ No violations found.</strong></p>
{{end}}

{{if .JIRAKeys}}
<h3>JIRA Tickets Raised</h3>
<p>{{range $i, $k := .JIRAKeys}}{{if $i}}, {{end}}{{$k}}{{end}}</p>
{{end}}

<h3>Cleanup</h3>
<p>
  <strong>Deleted:</strong> {{len .Cleanup.Deleted}} &nbsp;|&nbsp;
  <strong>Skipped:</strong> {{len .Cleanup.Skipped}} &nbsp;|&nbsp;
  <strong>Errors:</strong> {{len .Cleanup.Errors}}
</p>
{{if .Cleanup.Deleted}}
<ul>{{range .Cleanup.Deleted}}<li>{{.}}</li>{{end}}</ul>
{{end}}

<hr>
<p style="font-size:11px;color:#aaa">Generated by Pruner &mdash; AG Image Hygiene Automation</p>
</body>
</html>
`))

func RenderHTML(r *NamespaceReport) (string, error) {
	var buf bytes.Buffer
	if err := htmlTemplate.Execute(&buf, r); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func RenderText(r *NamespaceReport) string {
	var buf bytes.Buffer
	buf.WriteString("=== Image Hygiene Report ===\n")
	buf.WriteString("Namespace : " + r.Namespace + "\n")
	buf.WriteString("Cluster   : " + r.ClusterURL + "\n")
	buf.WriteString("Scanned   : " + r.ScannedAt.Format("2006-01-02 15:04 UTC") + "\n\n")
	buf.WriteString("Total Images : " + itoa(r.TotalImages) + "\n")
	buf.WriteString("Violations   : " + itoa(len(r.Violations)) + "\n")
	buf.WriteString("  HIGH   : " + itoa(r.CountBySeverity("HIGH")) + "\n")
	buf.WriteString("  MEDIUM : " + itoa(r.CountBySeverity("MEDIUM")) + "\n")
	buf.WriteString("  LOW    : " + itoa(r.CountBySeverity("LOW")) + "\n\n")

	if len(r.Violations) > 0 {
		buf.WriteString("VIOLATIONS\n")
		buf.WriteString("----------\n")
		for _, v := range r.Violations {
			buf.WriteString("  [" + v.Severity + "] " + v.ImageRef + " | " + v.RuleType + " | " + itoa(v.AgeDays) + "d\n")
		}
		buf.WriteString("\n")
	}

	if len(r.JIRAKeys) > 0 {
		buf.WriteString("JIRA Tickets: ")
		for i, k := range r.JIRAKeys {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(k)
		}
		buf.WriteString("\n")
	}

	buf.WriteString("\nDeleted: " + itoa(len(r.Cleanup.Deleted)) +
		" | Skipped: " + itoa(len(r.Cleanup.Skipped)) +
		" | Errors: " + itoa(len(r.Cleanup.Errors)) + "\n")
	return buf.String()
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	result := ""
	for n > 0 {
		result = string(rune('0'+n%10)) + result
		n /= 10
	}
	return result
}
